### ISSUE TITLE
Provide credentials thru environment variable?

### ISSUE THREAD

**Issue by anishkny** [dropbox/dbxcli#104]
It is often useful in CI systems etc to provide credentials via an environment variable. Is this possible in dbxcli?

PS: Holy crap @diwakergupta its been a long time and no see! ✋

**Comment by diwakergupta** [comment]
@anishkny hola!! 👋 

Will cmdline flags work or you absolutely need env variables? I'll look into it.

**Comment by vaithak** [comment]
@diwakergupta I have added the feature to provide keys using environment variables in PR #107 . Please review it. Thanks.

**Comment by anishkny** [comment]
> Will cmdline flags work or you absolutely need env variables? I'll look into it.

cmdline flags should be fine although env vars is a commonly used idiom elsewhere. #107 seems promising!
