### ISSUE TITLE
Upload problems

### ISSUE THREAD

**Issue by bolau** [dropbox/dbxcli#108]
Hi,

upload doesn't work for me, and the error messages don't really help:

```
$ ~/bin/dbxcli put source.pkl /
Uploading 774 MiB/774 MiB
Error: Error in call to API function "files/upload_session/finish": HTTP header "Dropbox-API-Arg": commit.path: The root folder is unsupported.

$ ~/bin/dbxcli put source.pkl "/Team-Ordner „XXX“/"
Error: unexpected end of JSON input
```

This is release v2.1.1. Is this a bug or am I doing something wrong?

Best, Boris

**Comment by bolau** [comment]
The upload works without a target parameter, problem solved for me.

**Comment by susan51531** [comment]
![image](https://user-images.githubusercontent.com/2595468/51262090-99833580-19ec-11e9-8880-43c8bfb3196d.png)
As for me, it will output this message after uploaded 16M/85M.
It's ok after I split this file by 10MB.

**Comment by mixu00** [comment]
The same error message with version 2.1.2

$ ./dbxcli version
dbxcli version: v2.1.2
SDK version: 5.2.0
Spec version: 097e9ba

$ ./dbxcli MVI_3933.AVI
Error: Error in call to API function "files/upload_session/append": HTTP header "Dropbox-API-Arg": unknown field 'cursor'

but with version 2.1.0 this seems to working fine.

$ ./dbxcli version
dbxcli version: v2.1.0
SDK version: 4.2.0
Spec version: 5389e5b

$ ./dbxcli put MVI_3933.AVI
Uploading 187 MiB/187 MiB

**Comment by Still34** [comment]
Could we get an update on this issue? I'm also experiencing the `unknown field` error.

**Comment by diwakergupta** [comment]
The latest release (v3.0.0) should fix this. Please give it a try, thanks for your patience.

@Still34 @justelad @mixu00
