### ISSUE TITLE
root.go does not exist.....

### ISSUE THREAD

**Issue by brightersun99** [dropbox/dbxcli#147]
/home/staff_test/go/src/github.com/dropbox/dbxcli
88typenoob$ ls
CHANGELOG.md Gopkg.toml   README.md    cmd          dbxcli       vendor
Gopkg.lock   LICENSE      build.sh     contrib      main.go
88typenoob$ 

?

**Comment by lfaraone** [comment]
Is there a question here? Please reference the [documentation](https://github.com/dropbox/dbxcli#instructions-for-building-yourself)
