### ISSUE TITLE
Add `logout` or `revoke` command

### ISSUE THREAD

**Issue by waits** [dropbox/dbxcli#16]
There's currently no way to log out unless you know where the auth token is stashed and go delete it manually. A simple `logout`/`revoke` command would need to do two things:

1. Call `https://api.dropboxapi.com/2/auth/token/revoke` to revoke the active token
2. Delete `~/.config/dbxcli/auth.json`

**Comment by arafatx** [comment]
Oh my ... spending more than 3 hours looking for reauthorization, finally that is the directory it stored. should have put this in the main documentation in Beginner section !
