### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by diwakergupta** [dropbox/dbxcli#167]
Hi all, I started this project while I was at Dropbox. It obviously hasn't been maintained since I left (just look at the issues and commits). I was wondering if Dropbox would want to / prefer transferring this project (and https://github.com/dropbox/dropbox-sdk-go-unofficial) to me?

I can obviously clone the repos, but would like to preserve existing issues etc if possible.

cc/ @rajatgoel (not sure who else at Dropbox I can tag 🤔 )

**Comment by rajatgoel** [comment]
Hi @diwakergupta, how are you :)

I asked open-source team internally and they are wondering if you would be interested in getting write access to the repo to continue contributing to it. That approach has the benefit of all the existing imports working as-is. Also keeping them under "dropbox/" gives them a little more credibility even though Dropbox is not actively able to invest in these projects right now :(

What do you think?

**Comment by diwakergupta** [comment]
> Hi @diwakergupta, how are you :)
> 
> I asked open-source team internally and they are wondering if you would be interested in getting write access to the repo to continue contributing to it. That approach has the benefit of all the existing imports working as-is. Also keeping them under "dropbox/" gives them a little more credibility even though Dropbox is not actively able to invest in these projects right now :(
> 
> What do you think?

👋🏽 @rajatgoel ! Sure, I'm happy to try this route but I'd like to request admin access since I'd like to be able to make changes to Github workflows, use GH actions etc which are hard to do with write access only. LMK!

**Comment by rajatgoel** [comment]
Hi. The team has granted write permission to begin with (they have never had to grant admin permission before so want to evaluate that before granting it). 

In the meantime if you get blocked somewhere because of missing admin permission, do ping and they will be happy to help.
