### ISSUE TITLE
Make `ls` list files in multiple columns

### ISSUE THREAD

**Issue by waits** [dropbox/dbxcli#17]
It would be nice if the `ls` command listed files in columns so more can fit on a screen. Most/all unix-based `ls` commands do this, for example:

```
$ ls /etc/alphabet
alpha  charlie  echo     golf   india
bravo  delta    foxtrot  hotel  juliett

$ ls /srv/random-rails-app
app  config     db       Gemfile.lock  log     Rakefile  tmp
bin  config.ru  Gemfile  lib           public  test      vendor
```

Whereas this tool's output is:

```
$ dbxcli ls /some-folder
alpha
bravo
charlie
delta
...
```

The output of the `--long` option would of course remain unchanged.

**Comment by GrantSeltzer** [comment]
https://github.com/dropbox/dbxcli/pull/24

**Comment by waits** [comment]
Thanks @GrantSeltzer!
