### ISSUE TITLE
Unable to Re-Setup Dropbox connection

### ISSUE THREAD

**Issue by jrdnr** [dropbox/dbxcli#184]
I had dbxcli.exe set up and working, then today it started throwing an error that the app was disabled.  I tried to figure out a way to fix it on the Dropbox app side but when I couldn't find a way to reenable it I figured I should be able to just remove the app and re-set it up.  But now I get the erorr

> Error: invalid_access_token/.

How can I re-set all the tokens on my local system so I can re-setup the connection to dropbox?

**Comment by funline** [comment]
I have this problem too ((

**Comment by siffegh** [comment]
Ditto. I disconnected the app from Dropbox, renamed auth.json, and entered 'dbxcli account' at the command line. 
That returned the 'Go to https://www.dropbox.com...' URL to allow access, but when going there, I got a screen with 'This app is currently disabled.' Unfortunately, this looks like DB has disabled access via dbxcli. Hope I'm wrong!

**Comment by jrdnr** [comment]
> renamed auth.json

Where was the auth.json file? I don't remember seeing one anywhere.

**Comment by siffegh** [comment]
> > renamed auth.json
> 
> Where was the auth.json file? I don't remember seeing one anywhere.

On Win - C:\Users\<your username>\.config\dbxcli

**Comment by siffegh** [comment]
Doh, should be C:\Users\your username_backslash_.config\dbxcli

**Comment by rvdsteege** [comment]
I'm also having issues. The following error occurs when trying to upload files:

```
Error: Error in call to API function "files/upload": This app is currently disabled.
```

Like @siffegh said, after moving the `~/.config/dbxcli/auth.json` file out of its place, I got the "Go to https://www.dropbox.com/..." message when trying `dbxcli account`, but visiting the URL results in a message:

```
This app is currently disabled.
```

**Comment by jrdnr** [comment]
Sounds like we all need to open drop box support tickets. As long as dbxcli is supported a native command to clear the cashed info in the `config.json` file would be nice. But from what everyone is saying the error about the app being disabled sounds like drop box changed something on their end.

**Comment by gioxx** [comment]
This is the reply to my ticket (escalated to API support engineer):
![immagine](https://user-images.githubusercontent.com/1768601/161971184-c9b37c2a-33e6-4e34-8448-16bcba1b96e6.png)

I'm trying to contact my Dbox Customer Success Manager to discuss it.

**Comment by rvdsteege** [comment]
Thank you for sharing, @gioxx. Is Dropbox not "the creator" of `dbxcli`? This repository is in the https://github.com/dropbox/ organisation on GitHub… :confused:

**Comment by gioxx** [comment]
@rvdsteege exactly. This is the point.

![immagine](https://user-images.githubusercontent.com/1768601/161972897-448ae39a-7741-48fd-9a46-5e816f8545af.png)

**Comment by greg-db** [comment]
Thanks for the report all. This should be working again now.

**Comment by siffegh** [comment]
Thanks, all :-)

**Comment by funline** [comment]
thanks for all!
