### ISSUE TITLE
Have seperate commands for `rm` and `rmdir`

### ISSUE THREAD

**Issue by GrantSeltzer** [dropbox/dbxcli#25]
Would there be interest for this feature? I think most people using the CLI will be more technical and for the sake of making this cli consistent with standard coreutils would appreciate needing to `rmdir` a directory.

**Comment by waits** [comment]
Either that or a `-r` flag. It's a little too easy to delete a directory with contents.

**Comment by GrantSeltzer** [comment]
#28

**Comment by diwakergupta** [comment]
Fixed by #28
