### ISSUE TITLE
Recursive and force flags for rm

### ISSUE THREAD

**Issue by GrantSeltzer** [dropbox/dbxcli#26]
Would there be interest in this feature? I brought up the other issue about having `rmdir`, regardless of whether or not this is wanted there should be a blocker for removing non-empty directories.

**Comment by charignon** [comment]
See #31

**Comment by GrantSeltzer** [comment]
Force may need to be implemented along with features for prompting users for confirmation that they want to delete. The `-f` would just be to silent those prompts.
