### ISSUE TITLE
Authorization error - app has reached its team limit

### ISSUE THREAD

**Issue by murray-grant-fe** [dropbox/dbxcli#47]
Hi, 

I'm getting an error when using the pre-built Windows binary when authorizing my dropbox account. 

It's a dropbox error when I paste the url into my browser: `This app has reached its team limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's team limit.`

![capture](https://cloud.githubusercontent.com/assets/5770871/17877402/60ec23a4-6926-11e6-8f23-653444cdee5b.PNG)

```
murray.grant@FE-DEV-IOS C:\Users\murray.grant\Downloads
> dbxcli-windows-amd64.exe team list-members
1. Go to https://www.dropbox.com/1/oauth2/authorize?client_id=xxe04eai4wmlitv&response_type=code&state=state
2. Click "Allow" (you might have to log in first).
3. Copy the authorization code.
Enter the authorization code here:
```

Can you increase your app limit, please. Or should I be doing something else to resolve this?

Regards Murray

**Comment by diwakergupta** [comment]
Thanks @murray-grant-fe and sorry about that! Can you try again? Should be fixed now. Please reopen if not.
