### ISSUE TITLE
Can't authorize team management 

### ISSUE THREAD

**Issue by tplants** [dropbox/dbxcli#58]
Error message from the OAuth authorization URL:

> This app is in development mode and can't be authorized by more teams. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status.

I would love to use the CLI to streamline user provisioning, so would either like to get added to the development list or have production status enabled for the app.

**Comment by diwakergupta** [comment]
Whoops, sorry about that @tplants ! On the other hand, glad to see I've hit my caps on a "development" status. I've filed for production status so this should hopefully be resolved shortly. I'll update the issue when I have confirmation. Thanks for reporting!

**Comment by tplants** [comment]
thanks! Looks like a great tool for the ol' toolbox.

**Comment by diwakergupta** [comment]
@tplants can you download the latest release and try again? This should be fixed now. Once you verify, I can close this out. Thanks again for the report!

**Comment by diwakergupta** [comment]
@tplants I'm closing this out; feel free to reopen if the latest release doesn't work for you.

**Comment by tplants** [comment]
Sorry for delay. This worked slick.

Thanks!
