### ISSUE TITLE
Asks for authentication code on each run [Linux]

### ISSUE THREAD

**Issue by hotice** [dropbox/dbxcli#6]
Each time I run a dbxcli command, it asks for the Dropbox authorization code. Should this be saved to some configuration file?

This occurs using the latest v0.1.1 release (binary downloaded from GitHub) under Ubuntu 16.04 64bit.

Let me know if you need more info.

**Comment by satori** [comment]
Have you authorized application?
Could you check that auth token is saved in `$HOME/.config/dbxcli/auth.conf`?

**Comment by hotice** [comment]
Yes, I tried authorizing it a few times and then I gave up :) The app didn't create the ``$HOME/.config/dbxcli/`` folder, so I assume that's why...

**Comment by hotice** [comment]
After I created the ``$HOME/.config/dbxcli/`` folder manually, the app was able to create the ``auth.conf`` file and save the access token. So the issue here is that dbxcli doesn't automatically create its config directory.

**Comment by satori** [comment]
It was fixed in #3, but not released yet. We'll make new release soon.
Thanks for information!

**Comment by hotice** [comment]
Thanks!
