### ISSUE TITLE
Generating authorization code no longer works

### ISSUE THREAD

**Issue by slzarate** [dropbox/dbxcli#61]
When you first do a command using DBXCLI, it asks you to go to the following URL:
`https://www.dropbox.com/1/oauth2/authorize?client_id=mvhz183vwqibe7q&response_type=code&state=state`

This URL now appears to be broken. The error is as follows:

> Error (400)
> It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.
> 
> 
> More details for developers
> 
> Invalid client_id: "mvhz183vwqibe7q".

**Comment by diwakergupta** [comment]
@slzarate that looks like an old binary. Can you download the latest release from https://github.com/dropbox/dbxcli/releases/latest and try again?

**Comment by slzarate** [comment]
Ah... that worked. Good to know that updates change the URL as well. Thanks!

**Comment by diwakergupta** [comment]
Well, they normally don't :) This was a special case (which is why I updated the major version to indicate a breaking change) -- I had to switch the app tokens for some security reasons, and thus the URLs were changed too.
