### ISSUE TITLE
Unable to Authorize App

### ISSUE THREAD

**Issue by garyemerson** [dropbox/dbxcli#64]
I ran `go get -u github.com/dropbox/dbxcli` and then `./dbxcli du`. This is the auth url I'm given: `https://www.dropbox.com/1/oauth2/authorize?client_id=mvhz183vwqibe7q&response_type=code&state=state`

and this is what I get when I visit:
![screen shot 2017-02-24 at 10 07 34 pm](https://cloud.githubusercontent.com/assets/5726308/23328726/f58eda4e-fadd-11e6-8649-fd1589a0c083.png)

Am I doing something wrong here?

**Comment by diwakergupta** [comment]
@garyemerson known issue, please download the [latest release](https://github.com/dropbox/dbxcli/releases/latest) and try again. Thanks!

**Comment by diwakergupta** [comment]
More specifically, `dbxcli` is no longer `go get`-able -- you need to use the pre-built binaries. This is because we no longer embed the security tokens used for the production app in the source code.

**Comment by garyemerson** [comment]
Hmm, I see. I wanted to use this on my headless raspberry pi and I think my only option is compiling from src. Is that possible? From `build.sh` it looks like I need a few secret keys and stuff.

**Comment by diwakergupta** [comment]
@garyemerson I'm happy to generate builds for you if you can send me the OS/platform combo (seems like 32-bit ARM?). To do your own builds yes you'd need to register your own apps and use your own keys.

**Comment by garyemerson** [comment]
Awesome, that'd be great. Just created #65!

**Comment by diwakergupta** [comment]
Should be fixed now that #65 is merged. I'm pushing new builds, please download the latest ARM build and LMK if it works!

**Comment by garyemerson** [comment]
It works great, thanks a bunch!
