### ISSUE TITLE
How do I install this program?

### ISSUE THREAD

**Issue by mbigras** [dropbox/dbxcli#67]
I'm running macOS 10.12.1.

How do I install this program?

I downloaded the `dbxcli-darwin-amd64` file from the [releases](https://github.com/dropbox/dbxcli/releases) page. I tried adding executable permissions and running it but it failed:

```
$ chmod +x dbxcli-darwin-amd64
$ ./dbxcli-darwin-amd64
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x148048f, 0x21)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbff810 sp=0x7fff5fbff7f0
runtime.goenvs()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/os_darwin.go:108 +0xa0 fp=0x7fff5fbff840 sp=0x7fff5fbff810
runtime.schedinit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbff880 sp=0x7fff5fbff840
runtime.rt0_go(0x7fff5fbff8b8, 0x1, 0x7fff5fbff8b8, 0x0, 0x0, 0x1, 0x7fff5fbffa58, 0x0, 0x7fff5fbffa6e, 0x7fff5fbffaaa, ...)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbff888 sp=0x7fff5fbff880
```

**Comment by diwakergupta** [comment]
Quick Googling indicates a lot of people run into this if they are some anti-virus software etc on their machine, e.g. https://github.com/golang/go/issues/16730 and https://github.com/golang/go/issues/8801

Can you try some other Go binaries? That will help isolate if this is a problem with how `dbxcli` is built, or something specific on your machine.

**Comment by mbigras** [comment]
@diwakergupta Thank you for getting back to me. Yes I've been reading around and I'm pretty sure the problem is because of my work machines antivirus [Cylance](https://www.cylance.com/en_us/home.html).

* Do you know what the fix is?
* Do I need to install Go along with the `dbxcli-darwin-amd64` exe?

This is my version of Cylance:

![](https://www.dropbox.com/s/0j53jimyuhw1ajm/Screenshot%202017-03-24%2013.40.41.png?dl=1)

It looks like one [solution](https://github.com/junegunn/fzf/issues/849#issuecomment-284272548) was the change the policy of Cylance but I'm curious if there are any other workarounds.

**Comment by lfaraone** [comment]
I'd report it as a false positive to Cylance -- it looks like they just have a particularly aggressive filter?

Go binaries are by default statically linked; installing Go is only needed if you want to rebuild it from source.

**Comment by mbigras** [comment]
This is an issue with Cylance. The fix is to contact your IT department and ask them to adjust your policy.
