### ISSUE TITLE
v2.0.2 in Windows ls not returning results unless verbose

### ISSUE THREAD

**Issue by ryallappasetty** [dropbox/dbxcli#68]
When I run dbxcli with the ls / it does not return anything. if I run it verbosely e.g. dbxcli ls / -v it returns:

2017/03/20 20:03:15 client.go:1510: arg: &{ false false false false}
2017/03/20 20:03:15 client.go:1527: req: &{POST https://api.dropboxapi.com/2/files/list_folder HTTP/1.1 1 1 map[Content-Type:[application/json]] {0xc042067950} 0x653400 124 [] false api.dropboxapi.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}
2017/03/20 20:03:16 client.go:1531: resp: &{200 OK 200 HTTP/1.1 1 1 map[X-Dropbox-Http-Protocol:[None] X-Frame-Options:[SAMEORIGIN] Content-Type:[application/json] Pragma:[no-cache] X-Server-Response-Time:[186] Server:[nginx] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Dropbox-Request-Id:

plus directory information and file names.

Running on fully patched Windows 10.

**Comment by diwakergupta** [comment]
@ryallappasetty Weird. I don't have a Windows machine handy for testing, so it'll be a bit hard for me to debug this immediately. Are you comfortable building/testing dbxcli? Maybe you can help me figure this out!

**Comment by diwakergupta** [comment]
@ryallappasetty I'm finally able to test on Windows and am able to repro this bug, thanks again for the report! I'm investigating, will update once I have more info.

**Comment by diwakergupta** [comment]
Alright, `dbxcli ls -l` works just fine so it's just a display issue. I believe the bug is in `golumns.Display` -- @GrantSeltzer can you take a look?

**Comment by diwakergupta** [comment]
Specifically, I think `GetSize` (https://github.com/golang/crypto/blob/master/ssh/terminal/util.go#L81) doesn't work as-is on Windows. 

On that note, I'm also considering if it's worth pulling in the crypto/ssh dependency just for terminal size. Will explore options.

**Comment by diwakergupta** [comment]
@ryallappasetty should be fixed with v2.0.4 onwards -- can you download the latest release and try?
