### ISSUE TITLE
Fails on most uploads and downloads

### ISSUE THREAD

**Issue by hotice** [dropbox/dbxcli#7]
Pretty much all uploads and downloads fail and this is displayed:
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8b7400, 0xc82000e0f0)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
github.com/dropbox/dbxcli/cmd.put(0xbe2860, 0xc82000eeb0, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/cmd/put.go:60 +0x6a4
github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra.(*Command).execute(0xbe2860, 0xc82000ee60, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra/command.go:565 +0x62c
github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xbe3260, 0xbe2860, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra/command.go:656 +0x55c
github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra.(*Command).Execute(0xbe3260, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra/command.go:615 +0x2d
github.com/dropbox/dbxcli/cmd.Execute()
	/home/travis/gopath/src/github.com/dropbox/dbxcli/cmd/root.go:218 +0x23
main.main()
	/home/travis/gopath/src/github.com/dropbox/dbxcli/main.go:43 +0x14
```

Using Ubuntu 16.04 64bit and the 64bit dbxcli binary downloaded from GitHub (but this also occurs with older versions).

**Comment by diwakergupta** [comment]
@hotice I just tried this and both uploads and downloads work fine for me. Note that right now you *must* explicitly supply _both_ source and destination paths like so:

```
$ dbxcli put <src> <dst>
$ dbxcli get <src> <dst>
```

I will improve the error handling and usage message to make this clear. Please try again and close this out if it works OK for you.

**Comment by hotice** [comment]
But then how come it works with some files but it doesn't with most? Anyway, can you please post an example, I can't find an example command anywhere and it looks like my logic doesn't work, because using:

```$ dbxcli put /home/andrei/dbxcli/*.png dbxcli/```
does not work. I mean, it works exactly the same as when not specifying a path. I actually have some 5 screenshots in a folder and using either the command above or a command that doesn't uses any paths, dbxcli uploads exactly 1 file (always the same). I also tried specifically uploading any of the others and it fails.

**Comment by diwakergupta** [comment]
Ah, we don't support shell expansion or multiple files just yet. So you need to upload/download one file at a time. So in your case, it would be like:

```
$ dbxcli put /home/andrei/dbxcli/foo.png dbxcli/foo.png
$ dbxcli put /home/andrei/dbxcli/bar.png dbxcli/bar.png
# and so on..
```

Does that make sense? Please do file a feature request for this so we can track and prioritize!

**Comment by hotice** [comment]
Absolutely, thank you! What I failed to do in my test was to also specify the filename for the Dropbox path (I only used "dbxcli/", without adding the file name). I still don't understand why it worked for a few files, it's pretty weird.

Hopefully my initial command will work soon :)

**Comment by diwakergupta** [comment]
Yep, hopefully! :smile: Am going to close this out now but please feel free to file a feature request!
