### ISSUE TITLE
Better output for ls

### ISSUE THREAD

**Issue by mikaelmantel** [dropbox/dbxcli#78]
Hello,

When i use ls for listing all my files in a directory, the output is very strange : 

![capture d ecran 2017-09-08 a 09 31 07](https://user-images.githubusercontent.com/7966573/30200746-80567216-9478-11e7-99ee-84f6cd66577e.png)

why the amount of whitespace is not fix ? or just use tabs ?

Thank you

**Comment by diwakergupta** [comment]
@mikaelmantel yes, it's not ideal. We do use tabs, but the output can still be warped depending on the size of your screen / terminal. We used to have better formatting in the past, but there were some platform specific dependencies that made the binaries fail on windows, so I had to trade-off formatting for more platform support.

If you do `ls -l` you should slightly better output. Meanwhile, suggestions / PRs are welcome!

**Comment by mikaelmantel** [comment]
Ok, i didn't know ! Thank you, i succeeded to parse with ls -l .
