### ISSUE TITLE
Support `ls` on files

### ISSUE THREAD

**Issue by diwakergupta** [dropbox/dbxcli#8]
Right now attempting `ls` on files fails:

```
$ ./dbxcli ls test.mp4
Error: path/not_folder/.
```

**Comment by waits** [comment]
I'll take a stab at this if you don't mind! I've been looking for more Go projects to contribute to, and I find this tool amazingly useful.

**Comment by diwakergupta** [comment]
Thanks @waits, go for it!

**Comment by waits** [comment]
Looks like the Dropbox API is generating that error; it doesn't allow a `list_folder` action to be performed on files. Unless you want to change the API, I think the best option would be to follow up on that error with a call to `get_metadata` on the filename and print that response data. As far as I can see `get_metadata` returns the same fields as `list_folder` (but only for one file), so the output would be the same.

There will obviously be a performance hit from making two requests, but I don't see a way around that with the current API. It'll only affect these (probably uncommon) ls-on-filename calls, anyways, so I don't think that will be a huge problem.
