### ISSUE TITLE
go build: Cannot use versionCmd

### ISSUE THREAD

**Issue by banool** [dropbox/dbxcli#86]
I'm trying to compile, but I'm running into the following error:

    Daniels-MBP:dbxcli daniel$ go build
    # _/Users/daniel/github/dbxcli
    ./main.go:43:24: cannot use versionCmd (type *"github.com/spf13/cobra".Command) as type *"github.com/dropbox/dbxcli/vendor/github.com/spf13/cobra".Command in argument to cmd.RootCmd.AddCommand

Prior to this I cloned the repo and ran these commands:

    go get github.com/dropbox/dbxcli/cmd
    go get github.com/dropbox/dropbox-sdk-go-unofficial/dropbox
    go get github.com/spf13/cobra
    go build

I feel like I should be able to just run `go build` on its own, but I'm not sure.

Go version: `1.9.2`.

If I remove the culprit line (43 in main.go) it builds successfully. However when I try to do the auth step by running a command (where it gives me a URL to authorise the app with the API) the page gives me a 400 error saying that the request is invalid (`Invalid client_id: "mvhz183vwqibe7q"`). That sounds like it warrants another issue though.

**Comment by diwakergupta** [comment]
@banool First, unless you're actually developing dbxcli, you shouldn't need to build from source. Just download the latest binary for your platform from the releases page:
https://github.com/dropbox/dbxcli/releases

Second, you shouldn't need to `go get` anything additional -- all the dependencies are vendored-in (see the `vendor` directory). So if you've cloned the repo, just running `go build` in the root directory should suffice.

Feel free to reopen if you're still running into any problems.

**Comment by banool** [comment]
Running `go build` on its own doesn't work. I still get the same error about `versionCmd`. When I remove the versionCmd line, like I said the auth step doesn't work, I still get that 400 error.

**Comment by diwakergupta** [comment]
@banool are you sure you are compiling in the correct directory? `vendor` directories only work if your GOROOT, GOPATH etc are all setup correctly. FWIW, I just did the following:

* Create a vanilla Ubuntu VM container on Google Cloud
* Install `go` and `git`
* Create `$HOME/go`
* Run `go get github.com/dropbox/dbxcli`
* `cd ~/go/src/github.com/dropbox/dbxcli`
* `go build`

This works perfectly fine. Can you add the output of `go env` on your system?

**Comment by diwakergupta** [comment]
Actually from your original post, seems like you are compiling from the directory `Users/daniel/github/dbxcli` -- this will *NOT* work. You need to create `$HOME/go` and then run `go get`. To learn more, see https://golang.org/doc/install#testing and https://golang.org/doc/code.html#Workspaces

**Comment by banool** [comment]
Ah that worked for me build wise. The output of `go env` is:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/daniel/.go"
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/23/rbh4ybd93gj9689ymmdflvcc0000gn/T/go-build113185276=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

I'm using `.go` as my go folder instead of `go`, which I imagine should be fine considering the `GOPATH` is set to it.

I still can't do the auth step. When it gives me the link to follow, I arrive at this page:

![400 error page](https://dl.dropboxusercontent.com/s/lbbo1njv0xyq86d/Screenshot%202017-12-30%2008.58.19.png?dl=0)

**Comment by diwakergupta** [comment]
@banool also expected. If you want to build and test dbxcli yourself locally, you'll need to register your own apps here: https://www.dropbox.com/developers/apps

**Comment by banool** [comment]
Ah. I feel there should maybe be instructions in the README or CONTRIBUTING files that tell newcomers how to do all of this, at least the API stuff. It wasn't readily apparent to me that this was necessary, nor is it obvious what to do now that I have to. For example, I see in `build.sh` that there are 3 different keys that it is referring to, but I'm only given one keypair when making an app. I infer by the names that the latter two are only for teams, but no doubt some people would be confused by this. Furthermore, replacing the keys in `build.sh` doesn't actually resolve the issue. Instead, you have to change the keys in the `root.go` file. I'll submit a pull request with appropriate instructions.
