### ISSUE TITLE
Bad authorization URL generated.

### ISSUE THREAD

**Issue by kunalkushwaha** [dropbox/dbxcli#9]
URL leads to 404 error with msg below.

More details for developers

``Invalid client_id: "t99asy5qf227urb".``

Actual command
```
$ dbxcli  ls
1. Go to https://www.dropbox.com/1/oauth2/authorize?client_id=t99asy5qf227urb&response_type=code&state=state
2. Click "Allow" (you might have to log in first).
3. Copy the authorization code.
Enter the authorization code here:
```

**Comment by diwakergupta** [comment]
@kunalkushwaha which release are you using? (run `dbxcli version`) I believe you are using an outdated binary. Bunch of breaking changes have gone in since then, so I recommend using the v1+ release (get the latest from https://github.com/dropbox/dbxcli/releases)

**Comment by kunalkushwaha** [comment]
Hi used latest code. 
Basically, I used ``go get github.com/dropbox/dbxcli``

**Comment by kunalkushwaha** [comment]
Great the binary downloaded from release section works! Thanks :)

**Comment by diwakergupta** [comment]
@kunalkushwaha yeah, building locally won't work. The release process plugs in a few different values for production that I didn't want to include as part of the source. Thanks for reporting though! LMK if you find the tool useful; lots to be done, PRs welcome!!

**Comment by PatNarciso** [comment]
I digg this tool!  and am finding it useful. 
I did just get stung by this issue; and learned (from this post) that the pre-compiled versions are ideal for testing.  

I would appreciate being able to configure the client_id.  
Is this something that can be done via 'export' variables upon build?

Thank you.
