### ISSUE TITLE
Can't get the suthorization code.

### ISSUE THREAD

**Issue by Vcwmz** [dropbox/dbxcli#92]
hello~ Is anyone here now?
i have download the dnxcli and go build. but when i use the commod " dbxcli ls ",three lables are displayed:
1.Go to https://www.dropbox.com/1/oauth2/authorizeclient_id=mvhz183vwqibe7q
&response_type=code&state=state
2. Click "Allow" (you might have to log in first).
3. Copy the authorization code.

I follow it and   i can't get into this site.

This is the error:  Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.

More details for developers
Invalid client_id: "mvhz183vwqibe7q"

**Comment by diwakergupta** [comment]
Please don't `go build` dbxcli yourself -- instead, download one of the pre-compiled binaries for your platform from the releases page (https://github.com/dropbox/dbxcli/releases)
