### ISSUE TITLE
dbxcli doesn't detect when OAuth2 token no longer works

### ISSUE THREAD

**Issue by simsong** [dropbox/dbxcli#94]
I was using the dbxcli and I disconnected it from the "connected apps" section. Now it doesn't work, which is what I was expecting. But I can't figure out how to reconnect it. How do I do that?

**Comment by simsong** [comment]
Apparently if you `logout` from the cli, you can then log back in with the `account` command. So the problem is that the cli doesn't handle the case properly when its OAuth2 token no longer works.

**Comment by lfaraone** [comment]
Can you provide output of what the error is in this case, and what it should be instead?

**Comment by simsong** [comment]
Unfortunately, I don't have the error output anymore.
